### ISSUE TITLE
Naught and Logging

### ISSUE THREAD

**Issue by jabalsad** [avdi/naught#42]
Hi,

I'm trying to create a null logger as follows:

    require "naught"
    require "logging"

    log = Logging.logger["test"]
    log.info

    NullLog = Naught.build do |config|
      config.mimic log.class
    end

    null_log = NullLog.new
    null_log.info

But I get the following error:
    in `<main>': undefined method `info' for <null:Logging::Logger>:NullLog (NoMethodError)

Does this have to do with the way Logging defines methods? It seems to do some magic.

**Comment by sferik** [comment]
Closing this issue. Please reopen it if it’s still an issue.
