### ISSUE TITLE
In JRuby: Mimic'd Object with "send" Method Uses Ruby's Object#send

### ISSUE THREAD

**Issue by sbellware** [avdi/naught#65]
Note: Problem found in JRuby 1.7.18. The problem doesn't occur in MRI 2.1.0.

Condition: A class has a method named "send", and a null object with mimic configured is created from that class

Action: Call the "send" method on the null object.

Result: Ruby's Object#send is invoked

For example...
```ruby
class MessageBus
  def send(msg)
  end
end

NullObject = Naught.build do |config|
  config.mimic MessageBus
end

n = NullObject.new
n.send 'some message'

# => NoMethodError: undefined method `some message' for <null:MessageBus>:NullObject
```
If the definition of the "send" method is added to the null object configuration, the problem doesn't occur:
```ruby
NullObject = Naught.build do |config|
  config.mimic MessageBus

  def send(msg)
  end
end

n = NullObject.new
n.send 'some message'
# ok, no error
```

**Comment by sferik** [comment]
If an error occurs in JRuby but not MRI, that sounds like an issue to be raised with the JRuby project, not Naught. /cc @headius @enebo

**Comment by enebo** [comment]
@sferik yeah I agree. @sbellware  open an issue on our project and we can try and figure out what is happening.  It might also be worth seeing whether this happens with JRuby 9.0.0.0.pre1 (not that we won't still fix it in 1.7.x but it is always good to know).

**Comment by headius** [comment]
Probably related to ownership of the #send method, i.e. we're not defining it in the right place. I assume BasicObject or Object are used as a template for methods not to mimic, right?

**Comment by sferik** [comment]
@headius Yes, exactly. See https://github.com/avdi/naught/blob/master/lib/naught/basic_object.rb.

**Comment by headius** [comment]
It looks like we're defining them in the right place. Please open a JRuby issue for this and we will investigate there.

```
~/projects/jruby $ jruby -e "p BasicObject.instance_methods.sort"
[:!, :!=, :==, :__id__, :__send__, :equal?, :instance_eval, :instance_exec, :itself, :object_id]

~/projects/jruby $ jruby -e "p Kernel.instance_methods.sort"
[:!~, :<=>, :===, :=~, :class, :clone, :com, :define_singleton_method, :display, :dup, :enum_for, :eql?, :extend, :freeze, :frozen?, :hash, :inspect, :instance_of?, :instance_variable_defined?, :instance_variable_get, :instance_variable_set, :instance_variables, :is_a?, :java, :java_annotation, :java_field, :java_implements, :java_name, :java_package, :java_require, :java_signature, :javafx, :javax, :kind_of?, :method, :methods, :nil?, :org, :private_methods, :protected_methods, :public_method, :public_methods, :public_send, :remove_instance_variable, :respond_to?, :respond_to_missing?, :send, :singleton_class, :singleton_methods, :taint, :tainted?, :tap, :to_enum, :to_java, :to_s, :trust, :untaint, :untrust, :untrusted?]
```

**Comment by sferik** [comment]
@headius I did notice that JRuby defines `#object_id` on `BasicObject`, while MRI defines `#object_id` on `Object`. Should I open an issue for that as well?

**Comment by headius** [comment]
Ah yes, please do.
