### ISSUE TITLE
Is Coveralls more annoyance than it is worth?

### ISSUE THREAD

**Issue by avdi** [avdi/naught#69]
I don't have time to look into alternative configurations, but I am open to the possibility that Coveralls commenting every time coverage changes by %0.001 is more noise than help. Thoughts, @sferik?

**Comment by sferik** [comment]
:+1: I completely agree about @coveralls There’s a new service called @codecov that claims to do the same thing but better. Want to try swapping that in? https://codecov.io/

**Comment by avdi** [comment]
Just took a quick stab at it, but the recommended travis config errorred out :-(

**Comment by stevepeak** [comment]
Hey @avdi, I'm the founder at @codecov and wanted to jump in and help so see what happened during your CI build. Could you provide me with a link to the Travis build that failed. Thanks!

**Comment by avdi** [comment]
Here it is: https://travis-ci.org/avdi/naught/builds/66235188

**Comment by stevepeak** [comment]
> Read more here: https://github.com/codecov/codecov-ruby

```diff
@@ .travis.yml @@
- before_install:
-  pip install codecov
- after_success:
-  codecov

@@ naught/spec/spec_helper.rb @@
+ require 'codecov'
+ SimpleCov.formatter = SimpleCov::Formatter::Codecov

@@ Gemfile @@
+ gem 'codecov', :require => false, :group => :test
```

Let me know if these changes work :) Cheers!

**Comment by sferik** [comment]
@stevepeak When I try implementing the change you suggest, I get the following output after running the tests in my development environment:

```json
{"message": "token or build not found", "meta": {"request": "19fb93a2-d8de-4830-bfe7-2eddd2d74ef9", "status": 400}, "uploaded": false}
```

This change also It also seems to generate a `tmp.json` artifact that is not removed, despite the fact that the upload seems to fail with a 400 error. I could add `tmp.json` to this project’s `.gitignore` but I would rather it just clean itself up.

**Comment by stevepeak** [comment]
@sferik this 400 would be expected when running locally with on token or CI build. 

I do notice the tmp.json [created here](https://github.com/codecov/codecov-ruby/blob/master/lib/codecov.rb#L21). I dont believe this line is actually necessary. I'll see to removing it.

**Comment by stevepeak** [comment]
@sferik was your project going to integrate with Codecov? Let me know how I can help out in any way. Thank you!

**Comment by sferik** [comment]
@stevepeak We tried it out but decided against it. Thanks anyway for your help!
